// ── Qualitech Sales Dashboard ── Code.gs ─────────────────────────────────────
// Reads from: V2 Qualitech_Sales_Report_2026_YTD_Jan_Apr29
// SSOT_ID: spreadsheet generated by Report Generator v2.0
//
// Report Generator v2.0 tab layout:
//   Row 1: merged title  (1 non-empty cell after merge — skipped by sheetToObjects)
//   Row 2: empty         (Salesperson / Dept / Top Clients / Pipeline tabs)
//   Row 3: column headers
//   Row 4+: data rows
//
// Exception — Raw Data tab (headers at row 2, not row 3):
//   Row 1: merged title
//   Row 2: 13 column headers  ← sheetToObjects picks this up correctly
//   Row 3+: data rows
//
// Exception — Executive Summary:
//   Row 1: merged title
//   Row 2: source info line
//   Row 4: KPI headers (Total Deals | Win Deals | Lost Deals | Waiting | Win Rate\n(Decided) | Win Revenue\n(THB) | Pipeline\n(THB) | Avg Win Deal\n(THB) | Best Month | Top Salesperson)
//   Row 5: KPI values  (Win Rate stored as "73.3%"  string — see pctFmt in generator)
//   Row 8: section header
//   Row 9: monthly headers (Month | Win Deals | Lost Deals | Waiting | Win Rate % | Win Revenue (THB) | Lost Revenue (THB) | Pipeline (THB) | vs Prior Month | Cumul. Win Rev (THB))
//   Row 10+: monthly data (Jan, Feb, …)  then TOTAL
//
// Exact column names per tab (from Report Generator v2.0):
//   Salesperson Performance: Salesperson | Total Deals | Win | Lost | Waiting | Win Rate % | Win Revenue (THB) | Lost Revenue (THB) | Avg Win Deal (THB)
//   Department Performance:  Department | Total Deals | Win | Lost | Win Rate % | Win Revenue (THB) | Total Revenue (THB)
//   Top Clients:             Rank | Client Name | Win Deals | Win Revenue (THB) | % of Win Rev | Dept | Top Salesperson
//   Pipeline (Waiting):      Rank | Client Name | Salesperson | Value (THB) | Dept | Month | Category | Age Note
//   Raw Data:                Action Date | Month | Week | Sale | Client Name | Value (raw) | Value (THB) | Status | Dept | Category | Task Title | Milestone % | Notes
//
// Status values in Raw Data: 'Win' | 'Lost' | 'Waiting'  (exact strings from source)
// Win Rate stored as percentage string "73.3%" (pctFmt output from generator)
// ─────────────────────────────────────────────────────────────────────────────

// Pre-aggregated report (Executive Summary, Salesperson Performance, etc.)
var SSOT_ID = "1CFNtkn8aXCnlONBou3ecFxiwuR0r9LHuoNqRDA_jXR4";

// Source-of-truth: RFQ-Job Process Record — Quotation tab
// Used for live raw rows in the filter bar (always up-to-date)
var SOURCE_ID = "1TWdKkoQsDgqgRgDd2g6MNG5P4pV7wImeuZ4Ec3DhYa0";
var MONTH_ABBR = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

function doGet(e) {
  var html = HtmlService.createHtmlOutputFromFile("Index")
    .setTitle("Qualitech Sales Dashboard")
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  return html;
}

function getSalesDashboardData() {
  var result = { ssot: null, error: null, fetchedAt: new Date().toISOString() };
  try { result.ssot = fetchAllTabs(SSOT_ID); }
  catch(e) { result.error = e.message + "\n" + e.stack; }
  return result;
}

// ── Main: read every relevant tab ────────────────────────────────────────────
function fetchAllTabs(id) {
  var ss         = SpreadsheetApp.openById(id);
  var sheetNames = ss.getSheets().map(function(s){ return s.getName(); });

  // 1. Executive Summary → KPIs + monthly breakdown
  var execSheet = ss.getSheetByName("Executive Summary") || ss.getSheets()[0];
  var exec      = parseExecutiveSummary(execSheet);

  // 2. Pre-aggregated tabs (each has title row 1, empty row 2, headers row 3)
  var salesTab   = ss.getSheetByName("Salesperson Performance");
  var deptTab    = ss.getSheetByName("Department Performance");
  var clientTab  = ss.getSheetByName("Top Clients");
  var pipeTab    = ss.getSheetByName("Pipeline (Waiting)");
  var rawTab     = ss.getSheetByName("Raw Data");  // headers at row 2 (no empty row)

  var salesRows    = salesTab   ? sheetToObjects(salesTab)   : [];
  var deptRows     = deptTab    ? sheetToObjects(deptTab)    : [];
  var clientRows   = clientTab  ? sheetToObjects(clientTab)  : [];
  var pipelineRows = pipeTab    ? sheetToObjects(pipeTab)    : [];
  // Prefer live data from RFQ source; fall back to pre-processed Raw Data tab
  var rawRows = fetchRawFromSource();
  if (!rawRows.length && rawTab) rawRows = sheetToObjects(rawTab);

  // 3. Normalise using exact column names from Report Generator v2.0
  var salespersons = normaliseSale(salesRows);
  var topClients   = normaliseClient(clientRows);
  var departments  = normaliseDept(deptRows);

  return {
    debug: {
      sheetNames:      sheetNames,
      execKPI:         exec.kpi,
      salesHeaders:    salesRows.length    > 0 ? Object.keys(salesRows[0])    : [],
      deptHeaders:     deptRows.length     > 0 ? Object.keys(deptRows[0])     : [],
      clientHeaders:   clientRows.length   > 0 ? Object.keys(clientRows[0])   : [],
      pipelineHeaders: pipelineRows.length > 0 ? Object.keys(pipelineRows[0]) : [],
      rawHeaders:      rawRows.length      > 0 ? Object.keys(rawRows[0])      : [],
      rawCount:        rawRows.length
    },
    // KPIs from Executive Summary
    totalRecords:   exec.kpi.totalDeals    || 0,
    wonCount:       exec.kpi.winDeals      || 0,
    lostCount:      exec.kpi.lostDeals     || 0,
    waitingCount:   exec.kpi.waiting       || 0,
    winRate:        exec.kpi.winRate       || 0,
    wonValue:       exec.kpi.winRevenue    || 0,
    lostValue:      exec.kpi.lostRevenue   || 0,
    waitingValue:   exec.kpi.pipeline      || 0,
    avgWinDeal:     exec.kpi.avgWinDeal    || 0,
    bestMonth:      exec.kpi.bestMonth     || "",
    topSalesperson: exec.kpi.topSalesperson || "",
    // Monthly breakdown
    monthly:        exec.monthly,
    // Aggregated tabs
    salespersons:   salespersons,
    topClients:     topClients,
    departments:    departments,
    pipelineRows:   pipelineRows,
    pipelineCount:  exec.kpi.waiting || pipelineRows.length,
    pipelineValue:  exec.kpi.pipeline || 0,
    // Raw rows for frontend filtering
    rawRows:        rawRows
  };
}

// ── Parse Executive Summary ───────────────────────────────────────────────────
// Generator writes:
//   Row 4: KPI label row  — cell[0] = "Total Deals"
//   Row 5: KPI value row  — Win Rate as "73.3%" string (pctFmt output)
//   KPI column positions:  0=Total Deals, 1=Win Deals, 2=Lost Deals, 3=Waiting,
//                          4=Win Rate%(string), 5=Win Revenue(THB), 6=Pipeline(THB),
//                          7=Avg Win Deal(THB), 8=Best Month(str), 9=Top Salesperson(str)
//   Row 9: monthly headers — cell[0] = "Month"
//   Row 10+: monthly data
function parseExecutiveSummary(sheet) {
  if (!sheet) return { kpi: {}, monthly: [] };
  var values = sheet.getDataRange().getValues();
  var kpi     = {};
  var monthly = [];
  var monthlyHeaders = null;
  var MONTH_NAMES = ["jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec","total"];

  for (var i = 0; i < values.length; i++) {
    var row   = values[i];
    var cell0 = String(row[0] || "").trim().toLowerCase();

    // KPI header row: cell[0] = "Total Deals"
    if (cell0 === "total deals") {
      if (i + 1 < values.length) {
        var v = values[i + 1];
        kpi.totalDeals     = toNum(v[0]);
        kpi.winDeals       = toNum(v[1]);
        kpi.lostDeals      = toNum(v[2]);
        kpi.waiting        = toNum(v[3]);
        // Win Rate stored as "73.3%" string (pctFmt: (decimal*100).toFixed(1)+'%')
        var wrStr = String(v[4] || "0").replace("%", "");
        var wrNum = toNum(wrStr);
        kpi.winRate        = wrNum > 1 ? wrNum : wrNum * 100;  // "73.3" → 73.3
        kpi.winRevenue     = toNum(v[5]);
        kpi.pipeline       = toNum(v[6]);
        kpi.avgWinDeal     = toNum(v[7]);
        // Best Month: "Apr (฿24,597,000)" → strip parenthetical
        kpi.bestMonth      = String(v[8] || "").split("(")[0].trim();
        // Top Salesperson: "Kanokporn (฿18,000,000)" → first word only
        kpi.topSalesperson = String(v[9] || "").split("(")[0].trim();
      }
    }

    // Monthly header row: cell[0] = "Month"
    if (cell0 === "month") {
      monthlyHeaders = row.map(function(h){ return String(h).trim(); });
    }

    // Monthly data rows: cell[0] matches month abbreviation or "total"
    if (monthlyHeaders && MONTH_NAMES.indexOf(cell0) !== -1) {
      var mRow = {};
      monthlyHeaders.forEach(function(h, j){ mRow[h] = row[j]; });
      monthly.push(mRow);
    }
  }

  // Derive lostRevenue from monthly TOTAL row
  // Monthly headers: Month | Win Deals | Lost Deals | Waiting | Win Rate % | Win Revenue (THB) | Lost Revenue (THB) | Pipeline (THB) | vs Prior Month | Cumul. Win Rev (THB)
  var totalRow = monthly.filter(function(r){
    return String(r["Month"] || "").toLowerCase() === "total";
  })[0];
  if (totalRow) {
    kpi.lostRevenue = toNum(totalRow["Lost Revenue (THB)"] || 0);
  }

  return { kpi: kpi, monthly: monthly };
}

// ── Normalise Salesperson Performance tab ─────────────────────────────────────
// Exact columns (Report Generator v2.0):
//   Salesperson | Total Deals | Win | Lost | Waiting | Win Rate % | Win Revenue (THB) | Lost Revenue (THB) | Avg Win Deal (THB)
// Win Rate % stored as "73.3%" string (pctFmt output)
// Win / Lost / Waiting = deal counts (not revenue)
function normaliseSale(rows) {
  return rows.map(function(r) {
    var wrStr = String(pick(r, ["Win Rate %", "Win Rate"]) || "0").replace("%", "");
    var wrNum = toNum(wrStr);
    return {
      sale:      pick(r, ["Salesperson", "Sale", "Name", "Rep"]),
      win:       toNum(pick(r, ["Win Revenue (THB)", "Win Revenue"])),
      lost:      toNum(pick(r, ["Lost Revenue (THB)", "Lost Revenue"])),
      waiting:   0,
      winDeals:  toNum(pick(r, ["Win", "Win Deals"])),
      lostDeals: toNum(pick(r, ["Lost", "Lost Deals"])),
      waitDeals: toNum(pick(r, ["Waiting", "Wait Deals"])),
      winRate:   wrNum > 1 ? wrNum : wrNum * 100,  // "73.3" → 73.3
      avgWin:    toNum(pick(r, ["Avg Win Deal (THB)", "Avg Win Deal"])),
      total:     toNum(pick(r, ["Total Deals", "Total"]))
    };
  }).filter(function(s){
    return s.sale && s.sale !== "—" && String(s.sale).toUpperCase() !== "TOTAL";
  }).sort(function(a, b){ return b.win - a.win; });
}

// ── Normalise Top Clients tab ─────────────────────────────────────────────────
// Exact columns (Report Generator v2.0):
//   Rank | Client Name | Win Deals | Win Revenue (THB) | % of Win Rev | Dept | Top Salesperson
function normaliseClient(rows) {
  return rows.map(function(r) {
    var name = pick(r, ["Client Name", "Client", "Account"]);
    if (!name || name === "—") return null;
    var win = toNum(pick(r, ["Win Revenue (THB)", "Win Revenue"]));
    return {
      client:  name,
      win:     win,
      lost:    0,
      waiting: 0,
      total:   win
    };
  }).filter(function(c){ return c && c.client && c.client !== "—"; })
    .sort(function(a, b){ return b.win - a.win; })
    .slice(0, 10);
}

// Normalise legacy department names (e.g. "PISB" → "PIS-B")
function normDeptName(name) {
  if (!name) return name;
  var n = String(name).trim();
  var MAP = { "PISB": "PIS-B", "PISA": "PIS-A", "PIS B": "PIS-B", "PIS A": "PIS-A" };
  return MAP[n] || n;
}

// ── Normalise Department Performance tab ──────────────────────────────────────
// Exact columns (Report Generator v2.0):
//   Department | Total Deals | Win | Lost | Win Rate % | Win Revenue (THB) | Total Revenue (THB)
// Win / Lost = deal counts (not revenue); no Lost Revenue column in this tab
// Win Rate % stored as "73.3%" string
function normaliseDept(rows) {
  return rows.map(function(r) {
    var win   = toNum(pick(r, ["Win Revenue (THB)", "Win Revenue"]));
    var total = toNum(pick(r, ["Total Revenue (THB)", "Total Revenue"]));
    var wrStr = String(pick(r, ["Win Rate %", "Win Rate"]) || "0").replace("%", "");
    var wrNum = toNum(wrStr);
    return {
      dept:        normDeptName(pick(r, ["Department", "Dept", "Division"])),
      win:         win,
      other:       total > win ? total - win : 0,
      total:       total || win,
      winRate:     wrNum > 1 ? wrNum : wrNum * 100,
      winDeals:    toNum(pick(r, ["Win", "Win Deals"])),
      lostDeals:   toNum(pick(r, ["Lost", "Lost Deals"])),
      total_deals: toNum(pick(r, ["Total Deals", "Total"]))
    };
  }).filter(function(d){
    return d.dept && d.dept !== "—" && String(d.dept).toUpperCase() !== "TOTAL";
  }).sort(function(a, b){ return b.total - a.total; });
}

// ── Fetch raw deals from RFQ-Job Process Record (Quotation tab) ───────────────
// Columns used: แผนก[2] | Customer Name[4] | วันที่ในใบเสนอราคา[8] |
//               มูลค่างาน (THB)[15] | Status[19] | Sales Officer[29] | Year[31]
// Status values in source: 'Win' | 'Lost' | 'Waiting' | 'Cancelled'
// Returns rows normalised to the same shape as the "Raw Data" tab so
// detectKeys() and filterAndRender() work without modification.
function fetchRawFromSource() {
  try {
    var ss    = SpreadsheetApp.openById(SOURCE_ID);
    var sheet = ss.getSheetByName("Quotation");
    if (!sheet) return [];

    var values = sheet.getDataRange().getValues();
    if (values.length < 2) return [];

    var currentYear = new Date().getFullYear();
    var allowedYears = [currentYear - 1, currentYear];  // e.g. [2025, 2026]
    var rows = [];

    for (var i = 1; i < values.length; i++) {
      var r = values[i];

      // Year filter — keep last 2 years
      var yr = parseInt(r[31]);
      if (allowedYears.indexOf(yr) === -1) continue;

      // Status filter — skip Cancelled; keep Win / Lost / Waiting
      var status = String(r[19] || "").trim();
      if (status !== "Win" && status !== "Lost" && status !== "Waiting") continue;

      // Derive "Jan 2025" style month from date
      var month = "";
      var d = r[8];
      if (d instanceof Date && !isNaN(d)) {
        month = MONTH_ABBR[d.getMonth()] + " " + d.getFullYear();
      }

      // Value — could be a number or string like "Unit rate"
      var val = r[15];
      var valNum = (typeof val === "number") ? val : parseFloat(String(val || "").replace(/[,฿\s]/g, ""));
      if (isNaN(valNum)) valNum = 0;

      rows.push({
        "Month":       month,
        "Sale":        String(r[29] || "").trim(),
        "Client Name": String(r[4]  || "").trim(),
        "Value (THB)": valNum,
        "Status":      status,
        "Dept":        normDeptName(String(r[2] || "").trim()),
        "Category":    String(r[5]  || "").trim()   // Project description
      });
    }
    return rows;
  } catch(e) {
    // If Dashboard script lacks access to SOURCE_ID, fall back silently
    return [];
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────
// Case-insensitive column picker — checks candidate names in order
function pick(obj, candidates) {
  if (!obj) return "—";
  var keys = Object.keys(obj);
  for (var c = 0; c < candidates.length; c++) {
    for (var k = 0; k < keys.length; k++) {
      if (keys[k].trim().toLowerCase() === candidates[c].toLowerCase()) {
        var v = obj[keys[k]];
        return (v !== null && v !== undefined && v !== "") ? v : "—";
      }
    }
  }
  return "—";
}

// Reads a sheet, skipping title/empty rows to find the real header row.
// Scans up to 6 rows for the first row with >= 2 non-empty cells:
//   Salesperson / Dept / Top Clients / Pipeline tabs: headers at row 3 (title+empty+headers)
//   Raw Data tab: headers at row 2 (title+headers, no empty row between)
function sheetToObjects(sheet) {
  if (!sheet) return [];
  var values = sheet.getDataRange().getValues();
  if (values.length < 2) return [];

  var headerIdx = -1;
  for (var i = 0; i < Math.min(values.length, 6); i++) {
    var nonEmpty = values[i].filter(function(v){
      return String(v || "").trim() !== "";
    });
    if (nonEmpty.length >= 2) {
      headerIdx = i;
      break;
    }
  }
  if (headerIdx < 0 || headerIdx + 1 >= values.length) return [];

  var headers = values[headerIdx].map(function(h){ return String(h).trim(); });
  var rows = [];
  for (var i = headerIdx + 1; i < values.length; i++) {
    var allEmpty = values[i].every(function(v){ return String(v || "").trim() === ""; });
    if (allEmpty) continue;
    var row = {};
    headers.forEach(function(h, j){ row[h] = values[i][j]; });
    rows.push(row);
  }
  return rows;
}

function toNum(v) {
  if (v === null || v === undefined || v === "" || v === "—" || v === "-") return 0;
  var n = parseFloat(String(v).replace(/[,฿%\s]/g, ""));
  return isNaN(n) ? 0 : n;
}
