// ── Qualitech Sales Dashboard ── Code.gs ─────────────────────────────────────
// Reads from: V2 Qualitech_Sales_Report_2026_YTD_Jan_Apr29
// SSOT_ID: the spreadsheet generated by the Report Generator script
//
// Tab layout (generated by Report Generator v2.0):
//   Row 1: merged title  (must skip)
//   Row 2: empty         (must skip)
//   Row 3: column headers
//   Row 4+: data rows
//
// Exception — Executive Summary:
//   Row 4: KPI headers (Total Deals | Win Deals | ... | Top Salesperson)
//   Row 5: KPI values
//   Row 9: Monthly headers (Month | Win Deals | ... | Cumul. Win Rev (THB))
//   Row 10+: monthly data (Jan, Feb, …), then TOTAL
// ─────────────────────────────────────────────────────────────────────────────

// ⚠ If the Report Generator writes to a different sheet, update this ID:
var SSOT_ID = "1aDvDAPCGVkhYw8ZA44fIfwP662phHUz4a3s-pAviX0g";

function doGet(e) {
  var html = HtmlService.createHtmlOutputFromFile("Index")
    .setTitle("Qualitech Sales Dashboard")
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  return html;
}

function getSalesDashboardData() {
  var result = { ssot: null, error: null, fetchedAt: new Date().toISOString() };
  try { result.ssot = fetchAllTabs(SSOT_ID); }
  catch(e) { result.error = e.message + "\n" + e.stack; }
  return result;
}

// ── Main: read every relevant tab ────────────────────────────────────────────
function fetchAllTabs(id) {
  var ss         = SpreadsheetApp.openById(id);
  var sheetNames = ss.getSheets().map(function(s){ return s.getName(); });

  // 1. Executive Summary → KPIs + monthly breakdown
  var execSheet = ss.getSheetByName("Executive Summary") || ss.getSheets()[0];
  var exec      = parseExecutiveSummary(execSheet);

  // 2. Pre-aggregated tabs (each has title row 1, headers row 3)
  var salesTab   = ss.getSheetByName("Salesperson Performance");
  var deptTab    = ss.getSheetByName("Department Performance");
  var clientTab  = ss.getSheetByName("Top Clients");
  var pipeTab    = ss.getSheetByName("Pipeline (Waiting)");

  var salesRows    = salesTab   ? sheetToObjects(salesTab)   : [];
  var deptRows     = deptTab    ? sheetToObjects(deptTab)    : [];
  var clientRows   = clientTab  ? sheetToObjects(clientTab)  : [];
  var pipelineRows = pipeTab    ? sheetToObjects(pipeTab)    : [];

  // 3. Normalise using exact column names from Report Generator v2.0
  var salespersons = normaliseSale(salesRows);
  var topClients   = normaliseClient(clientRows);
  var departments  = normaliseDept(deptRows);

  return {
    debug: {
      sheetNames:      sheetNames,
      execKPI:         exec.kpi,
      salesHeaders:    salesRows.length    > 0 ? Object.keys(salesRows[0])    : [],
      deptHeaders:     deptRows.length     > 0 ? Object.keys(deptRows[0])     : [],
      clientHeaders:   clientRows.length   > 0 ? Object.keys(clientRows[0])   : [],
      pipelineHeaders: pipelineRows.length > 0 ? Object.keys(pipelineRows[0]) : []
    },
    // KPIs from Executive Summary
    totalRecords:   exec.kpi.totalDeals    || 0,
    wonCount:       exec.kpi.winDeals      || 0,
    lostCount:      exec.kpi.lostDeals     || 0,
    waitingCount:   exec.kpi.waiting       || 0,
    winRate:        exec.kpi.winRate       || 0,
    wonValue:       exec.kpi.winRevenue    || 0,
    lostValue:      exec.kpi.lostRevenue   || 0,
    waitingValue:   exec.kpi.pipeline      || 0,
    avgWinDeal:     exec.kpi.avgWinDeal    || 0,
    bestMonth:      exec.kpi.bestMonth     || "",
    topSalesperson: exec.kpi.topSalesperson || "",
    // Monthly breakdown
    monthly:        exec.monthly,
    // Aggregated
    salespersons:   salespersons,
    topClients:     topClients,
    departments:    departments,
    pipelineRows:   pipelineRows,
    pipelineCount:  exec.kpi.waiting || pipelineRows.length,
    pipelineValue:  exec.kpi.pipeline || 0
  };
}

// ── Parse Executive Summary ───────────────────────────────────────────────────
// KPI header row: first cell = "Total Deals" (row 4 in generated sheet)
// KPI values row: next row after KPI headers (row 5)
// Monthly header row: first cell = "Month" (row 9)
// Monthly data rows: first cell = month abbreviation or "TOTAL"
function parseExecutiveSummary(sheet) {
  if (!sheet) return { kpi: {}, monthly: [] };
  var values = sheet.getDataRange().getValues();
  var kpi     = {};
  var monthly = [];
  var monthlyHeaders = null;
  var MONTH_NAMES = ["jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec","total"];

  for (var i = 0; i < values.length; i++) {
    var row   = values[i];
    var cell0 = String(row[0] || "").trim().toLowerCase();

    // KPI header row: cell[0] = "Total Deals"
    if (cell0 === "total deals" || cell0.indexOf("total deals") !== -1) {
      if (i + 1 < values.length) {
        var v = values[i + 1];
        kpi.totalDeals     = toNum(v[0]);
        kpi.winDeals       = toNum(v[1]);
        kpi.lostDeals      = toNum(v[2]);
        kpi.waiting        = toNum(v[3]);
        // Win Rate may be stored as decimal (0.733) or percent string ("73.3%")
        var wrRaw = String(v[4] || "0");
        var wrNum = toNum(wrRaw.replace("%",""));
        kpi.winRate        = wrNum > 1 ? wrNum : wrNum * 100; // normalise to 0–100
        kpi.winRevenue     = toNum(v[5]);
        kpi.pipeline       = toNum(v[6]);
        kpi.avgWinDeal     = toNum(v[7]);
        kpi.bestMonth      = String(v[8] || "").split("(")[0].trim(); // strip "(฿xxx)" suffix
        kpi.topSalesperson = String(v[9] || "").split("(")[0].trim();
      }
    }

    // Monthly header row: cell[0] = "Month"
    if (cell0 === "month") {
      monthlyHeaders = row.map(function(h){ return String(h).trim(); });
    }

    // Monthly data rows
    if (monthlyHeaders && MONTH_NAMES.indexOf(cell0) !== -1) {
      var mRow = {};
      monthlyHeaders.forEach(function(h, j){ mRow[h] = row[j]; });
      monthly.push(mRow);
    }
  }

  // Derive lostRevenue from monthly TOTAL row
  var totalRow = monthly.filter(function(r){
    return String(r["Month"] || "").toLowerCase() === "total";
  })[0];
  if (totalRow) {
    kpi.lostRevenue = toNum(
      totalRow["Lost Revenue (THB)"] || totalRow["Lost Revenue"] || 0
    );
  }

  return { kpi: kpi, monthly: monthly };
}

// ── Normalise Salesperson Performance tab ─────────────────────────────────────
// Actual columns (Report Generator v2.0):
//   Salesperson | Total Deals | Win | Lost | Waiting | Win Rate % | Win Revenue (THB) | Lost Revenue (THB) | Avg Win Deal (THB)
// Note: "Win" = win count, "Lost" = lost count, "Waiting" = waiting count
function normaliseSale(rows) {
  return rows.map(function(r) {
    var win  = toNum(pick(r, ["Win Revenue (THB)","Win Revenue","Won Revenue"]));
    var lost = toNum(pick(r, ["Lost Revenue (THB)","Lost Revenue","Lose Revenue"]));
    var wr   = toNum(String(pick(r, ["Win Rate %","Win Rate","Win%","Ach%"]) || "0").replace("%",""));
    return {
      sale:      pick(r, ["Salesperson","Sale","Name","Rep","Agent","Employee"]),
      win:       win,
      lost:      lost,
      waiting:   0,  // no waiting value per salesperson in this tab
      winDeals:  toNum(pick(r, ["Win","Win Deals","Won Deals","Win Count"])),
      lostDeals: toNum(pick(r, ["Lost","Lost Deals","Lost Count","Losses"])),
      waitDeals: toNum(pick(r, ["Waiting","Wait","Wait Deals"])),
      winRate:   wr > 1 ? wr : wr * 100,  // normalise to 0–100
      avgWin:    toNum(pick(r, ["Avg Win Deal (THB)","Avg Win Deal","Avg Win"])),
      total:     toNum(pick(r, ["Total Deals","Total Deals ","Total"]))
    };
  }).filter(function(s){ return s.sale && s.sale !== "—"; })
    .sort(function(a,b){ return b.win - a.win; });
}

// ── Normalise Top Clients tab ─────────────────────────────────────────────────
// Actual columns: Rank | Client Name | Win Deals | Win Revenue (THB) | % of Win Rev | Dept | Top Salesperson
function normaliseClient(rows) {
  return rows.map(function(r) {
    // Skip rank rows that are just numbers or emoji
    var nameRaw = pick(r, ["Client Name","Client","Customer","Company","Account","Name"]);
    if (!nameRaw || nameRaw === "—") return null;
    var win = toNum(pick(r, ["Win Revenue (THB)","Win Revenue","Won Revenue","Win","Won"]));
    return {
      client:  nameRaw,
      win:     win,
      lost:    toNum(pick(r, ["Lost Revenue (THB)","Lost Revenue","Lost"])),
      waiting: toNum(pick(r, ["Pipeline (THB)","Pipeline","Waiting"])),
      total:   toNum(pick(r, ["Total Revenue (THB)","Total Revenue","Total","Grand Total"])) || win
    };
  }).filter(function(c){ return c && c.client && c.client !== "—"; })
    .sort(function(a,b){ return b.total - a.total; })
    .slice(0, 10);
}

// ── Normalise Department Performance tab ─────────────────────────────────────
// Actual columns: Department | Total Deals | Win | Lost | Win Rate % | Win Revenue (THB) | Total Revenue (THB)
function normaliseDept(rows) {
  return rows.map(function(r) {
    var win   = toNum(pick(r, ["Win Revenue (THB)","Win Revenue","Won Revenue","Win"]));
    var total = toNum(pick(r, ["Total Revenue (THB)","Total Revenue","Grand Total","Total"])) || win;
    return {
      dept:    pick(r, ["Department","Dep Responsibility","Dept","Division","Team","Unit"]),
      win:     win,
      lost:    toNum(pick(r, ["Lost Revenue (THB)","Lost Revenue","Lost"])),
      waiting: toNum(pick(r, ["Pipeline (THB)","Pipeline","Waiting"])),
      total:   total
    };
  }).filter(function(d){ return d.dept && d.dept !== "—"; })
    .sort(function(a,b){ return b.total - a.total; });
}

// ── Helpers ───────────────────────────────────────────────────────────────────
// Case-insensitive column picker — checks candidate names in order
function pick(obj, candidates) {
  if (!obj) return "—";
  var keys = Object.keys(obj);
  for (var c = 0; c < candidates.length; c++) {
    for (var k = 0; k < keys.length; k++) {
      if (keys[k].trim().toLowerCase() === candidates[c].toLowerCase()) {
        var v = obj[keys[k]];
        return (v !== null && v !== undefined && v !== "") ? v : "—";
      }
    }
  }
  return "—";
}

// Reads a sheet, skipping title/empty rows to find the real header row.
// All tabs generated by Report Generator v2.0 have:
//   Row 1: merged title (1 non-empty cell after merge)
//   Row 2: empty
//   Row 3: column headers (>= 2 non-empty cells) ← detected here
//   Row 4+: data
function sheetToObjects(sheet) {
  if (!sheet) return [];
  var values = sheet.getDataRange().getValues();
  if (values.length < 2) return [];

  // Scan up to 6 rows to find the first row with >= 2 non-empty cells
  var headerIdx = -1;
  for (var i = 0; i < Math.min(values.length, 6); i++) {
    var nonEmpty = values[i].filter(function(v){
      return String(v || "").trim() !== "";
    });
    if (nonEmpty.length >= 2) {
      headerIdx = i;
      break;
    }
  }
  if (headerIdx < 0 || headerIdx + 1 >= values.length) return [];

  var headers = values[headerIdx].map(function(h){ return String(h).trim(); });
  var rows = [];
  for (var i = headerIdx + 1; i < values.length; i++) {
    var allEmpty = values[i].every(function(v){ return String(v || "").trim() === ""; });
    if (allEmpty) continue;
    var row = {};
    headers.forEach(function(h, j){ row[h] = values[i][j]; });
    rows.push(row);
  }
  return rows;
}

function toNum(v) {
  if (v === null || v === undefined || v === "" || v === "—") return 0;
  var n = parseFloat(String(v).replace(/[,฿%\s]/g,""));
  return isNaN(n) ? 0 : n;
}
